" no compatibility with vi
set nocompatible

" syntax highlighting
syntax on

if has("gui_running")
	colors desert
	" line numbers color
	hi LineNr guifg=grey45 guibg=grey20
endif

" enable filetype plugins and indents
filetype on
filetype plugin on
filetype indent on

set ttyfast

set tabstop=4 shiftwidth=4 softtabstop=4 autoindent smartindent

" prefer unix over windows over mac formats
set ffs=unix,dos,mac

" show tabs and trailing spaces
set listchars=tab:>·,trail:·
set list

" utf-8 default encoding
set enc=utf-8

" show line numbers
set number

" read file again, if it was changed outside of vim
set autoread

" use wildmenu
set wildmenu

" selection, cut/copy/paste
so $VIMRUNTIME/mswin.vim

" open/close NERDTree
nmap <silent><C-n> :NERDTreeToggle<CR>
imap <silent><C-n> <C-o>:NERDTreeToggle<CR>

" ignore some files in NERDTree
let NERDTreeIgnore=['\~$', '\.pyc$', '\.pyo$']
let NERDTreeQuitOnOpen=1

" Project settings
let g:proj_flags = "gimst"

" close file
ino <C-q> <C-o>:q<CR>
nno <C-q> :q<CR>

" some usefull hotkeys from my Eclipse
ino <C-d> <C-o>dd
nno <C-d> dd

" move lines in normal, insert and visual modes
nno <A-Down> :m+<CR>==
ino <A-Down> <Esc>:m+<CR>==gi
vno <A-Down> :m'>+<CR>gv=gv
nno <A-Up> :m-2<CR>==
ino <A-Up> <Esc>:m-2<CR>==gi
vno <A-Up> :m-2<CR>gv=gv

" tabulate/untabulate text
smap <Tab> <C-o>>
smap <S-Tab> <C-o><
ino <S-Tab> <C-o><<CR>

" tab management
ino <silent><C-t> <C-o>:tabnew<CR>
nno <silent><C-t> :tabnew<CR>

" don't bell or blink
set noeb
set vb t_vb=

" window maximization
if has('gui')
	au GUIEnter * :set lines=99999 columns=99999
endif

" filetype specific options

let ropevim_vim_completion = 1

augroup python
	au!
	au BufEnter,BufWinEnter *.py ino <buffer><silent> <C-Space> <C-r>=RopeCodeAssistInsertMode()<CR>
	au BufEnter,BufWinEnter *.py setlocal expandtab
augroup END

augroup html
	au!
	au BufEnter,BufWinEnter *.html setlocal noet
augroup END

