" no compatibility with vi
set nocompatible

" syntax highlighting
syntax on
colorscheme solarized
set background=dark

" enable filetype plugins and indents
filetype on
filetype plugin on
filetype indent on

set ttyfast

set tabstop=4 shiftwidth=4 softtabstop=4 autoindent smartindent

" prefer unix over windows over mac formats
set ffs=unix,dos,mac

" utf-8 default encoding
set enc=utf-8

" show line numbers
set number

" show cursor position
set ruler

" read file again, if it was changed outside of vim
set autoread

" use wildmenu
set wildmenu

" open/close NERDTree
nmap <silent><C-e> :NERDTreeToggle<CR>
imap <silent><C-e> <C-o>:NERDTreeToggle<CR>

" do not render html
let html_no_rendering = 1

" ignore some files in NERDTree
let NERDTreeIgnore = ['\~$', '\.pyc$', '\.pyo$', '\.o$']
let NERDTreeQuitOnOpen = 0

" close file
ino <C-q> <C-o>:q<CR>
nno <C-q> :q<CR>

" move lines in normal, insert and visual modes
nno <A-Down> :m+<CR>==
ino <A-Down> <Esc>:m+<CR>==gi
vno <A-Down> :m'>+<CR>gv=gv
nno <A-Up> :m-2<CR>==
ino <A-Up> <Esc>:m-2<CR>==gi
vno <A-Up> :m-2<CR>gv=gv

" tabulate/untabulate text
smap <Tab> <C-o>>
smap <S-Tab> <C-o><
ino <S-Tab> <C-o><<CR>

" don't bell or blink
set noeb
set vb t_vb=

" don't let sql completion ruin insert-mode
" disable annoying autocompletion on <Left>/<Right> keys
let g:ftplugin_sql_omni_key_right = 'stub'
let g:ftplugin_sql_omni_key_left = 'stub'
